/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreContractsUniqueIdentifier model module.
 * @module io.generated.model/NetCordaCoreContractsUniqueIdentifier
 * @version 1.0.0
 */
class NetCordaCoreContractsUniqueIdentifier {
    /**
     * Constructs a new <code>NetCordaCoreContractsUniqueIdentifier</code>.
     * @alias module:io.generated.model/NetCordaCoreContractsUniqueIdentifier
     * @param id {String} 
     */
    constructor(id) { 
        
        NetCordaCoreContractsUniqueIdentifier.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>NetCordaCoreContractsUniqueIdentifier</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContractsUniqueIdentifier} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContractsUniqueIdentifier} The populated <code>NetCordaCoreContractsUniqueIdentifier</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContractsUniqueIdentifier();

            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} externalId
 */
NetCordaCoreContractsUniqueIdentifier.prototype['externalId'] = undefined;

/**
 * @member {String} id
 */
NetCordaCoreContractsUniqueIdentifier.prototype['id'] = undefined;






export default NetCordaCoreContractsUniqueIdentifier;

