/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetCordaCoreContractsStateRef from './NetCordaCoreContractsStateRef';

/**
 * The NetCordaCoreContractsStaticPointer model module.
 * @module io.generated.model/NetCordaCoreContractsStaticPointer
 * @version 1.0.0
 */
class NetCordaCoreContractsStaticPointer {
    /**
     * Constructs a new <code>NetCordaCoreContractsStaticPointer</code>.
     * @alias module:io.generated.model/NetCordaCoreContractsStaticPointer
     * @param type {String} Java class name
     */
    constructor(type) { 
        
        NetCordaCoreContractsStaticPointer.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>NetCordaCoreContractsStaticPointer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContractsStaticPointer} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContractsStaticPointer} The populated <code>NetCordaCoreContractsStaticPointer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContractsStaticPointer();

            if (data.hasOwnProperty('pointer')) {
                obj['pointer'] = NetCordaCoreContractsStateRef.constructFromObject(data['pointer']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:io.generated.model/NetCordaCoreContractsStateRef} pointer
 */
NetCordaCoreContractsStaticPointer.prototype['pointer'] = undefined;

/**
 * Java class name
 * @member {String} type
 */
NetCordaCoreContractsStaticPointer.prototype['type'] = undefined;






export default NetCordaCoreContractsStaticPointer;

