/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetCordaCoreContractsStatePointer model module.
 * @module io.generated.model/NetCordaCoreContractsStatePointer
 * @version 1.0.0
 */
class NetCordaCoreContractsStatePointer {
    /**
     * Constructs a new <code>NetCordaCoreContractsStatePointer</code>.
     * @alias module:io.generated.model/NetCordaCoreContractsStatePointer
     * @param type {String} Java class name
     * @param pointer {Object} 
     */
    constructor(type, pointer) { 
        
        NetCordaCoreContractsStatePointer.initialize(this, type, pointer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, pointer) { 
        obj['type'] = type;
        obj['pointer'] = pointer;
    }

    /**
     * Constructs a <code>NetCordaCoreContractsStatePointer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:io.generated.model/NetCordaCoreContractsStatePointer} obj Optional instance to populate.
     * @return {module:io.generated.model/NetCordaCoreContractsStatePointer} The populated <code>NetCordaCoreContractsStatePointer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetCordaCoreContractsStatePointer();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('pointer')) {
                obj['pointer'] = ApiClient.convertToType(data['pointer'], Object);
            }
        }
        return obj;
    }


}

/**
 * Java class name
 * @member {String} type
 */
NetCordaCoreContractsStatePointer.prototype['type'] = undefined;

/**
 * @member {Object} pointer
 */
NetCordaCoreContractsStatePointer.prototype['pointer'] = undefined;






export default NetCordaCoreContractsStatePointer;

